<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="10" failed="0" ignored="3" total="13" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="CloudBlaze Automation" duration-ms="16486" started-at="2020-04-14T12:02:03Z" finished-at="2020-04-14T12:02:19Z">
    <groups>
      <group name="Smoke">
        <method signature="SqlToAdlsDM.verifySourceAdd()[pri:6, instance:com.Fullload_CDC.SqlToAdlsDM@193f604a]" name="verifySourceAdd" class="com.Fullload_CDC.SqlToAdlsDM"/>
        <method signature="SqlToAdlsDM.verifyAddDestination()[pri:7, instance:com.Fullload_CDC.SqlToAdlsDM@193f604a]" name="verifyAddDestination" class="com.Fullload_CDC.SqlToAdlsDM"/>
        <method signature="SqlToAdlsDM.verifyAddDataFlow()[pri:8, instance:com.Fullload_CDC.SqlToAdlsDM@193f604a]" name="verifyAddDataFlow" class="com.Fullload_CDC.SqlToAdlsDM"/>
        <method signature="SqlToAdlsDM.verifyScheduledFlow()[pri:9, instance:com.Fullload_CDC.SqlToAdlsDM@193f604a]" name="verifyScheduledFlow" class="com.Fullload_CDC.SqlToAdlsDM"/>
        <method signature="SqlToAdlsDM.verifyFlowOnMontioringScreen()[pri:10, instance:com.Fullload_CDC.SqlToAdlsDM@193f604a]" name="verifyFlowOnMontioringScreen" class="com.Fullload_CDC.SqlToAdlsDM"/>
        <method signature="SqltoAzuresql.verifySourceAdd()[pri:1, instance:com.Fullload_CDC.SqltoAzuresql@550ee7e5]" name="verifySourceAdd" class="com.Fullload_CDC.SqltoAzuresql"/>
        <method signature="SqltoAzuresql.verifyAddDestination()[pri:2, instance:com.Fullload_CDC.SqltoAzuresql@550ee7e5]" name="verifyAddDestination" class="com.Fullload_CDC.SqltoAzuresql"/>
        <method signature="SqltoAzuresql.verifyAddDataFlow()[pri:3, instance:com.Fullload_CDC.SqltoAzuresql@550ee7e5]" name="verifyAddDataFlow" class="com.Fullload_CDC.SqltoAzuresql"/>
        <method signature="SqltoAzuresql.verifyScheduledFlow()[pri:4, instance:com.Fullload_CDC.SqltoAzuresql@550ee7e5]" name="verifyScheduledFlow" class="com.Fullload_CDC.SqltoAzuresql"/>
        <method signature="SqltoAzuresql.verifyFlowOnMontioringScreen()[pri:5, instance:com.Fullload_CDC.SqltoAzuresql@550ee7e5]" name="verifyFlowOnMontioringScreen" class="com.Fullload_CDC.SqltoAzuresql"/>
      </group> <!-- Smoke -->
    </groups>
    <test name="CloudBlaze Tests" duration-ms="16486" started-at="2020-04-14T12:02:03Z" finished-at="2020-04-14T12:02:19Z">
      <class name="com.Fullload_CDC.SqlToAdlsDM">
        <test-method status="SKIP" signature="verifySourceAdd()[pri:6, instance:com.Fullload_CDC.SqlToAdlsDM@193f604a]" name="verifySourceAdd" duration-ms="0" started-at="2020-04-14T12:02:19Z" finished-at="2020-04-14T12:02:19Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.CloudBlaze.Base.BaseClass.getResult(BaseClass.java:215)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:533)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySourceAdd -->
        <test-method status="FAIL" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.Fullload_CDC.SqlToAdlsDM@193f604a]" name="getResult" is-config="true" duration-ms="1" started-at="2020-04-14T12:02:19Z" finished-at="2020-04-14T12:02:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name={null} status=CREATED method=SqlToAdlsDM.verifySourceAdd()[pri:6, instance:com.Fullload_CDC.SqlToAdlsDM@193f604a] output={null}]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.CloudBlaze.Base.BaseClass.getResult(BaseClass.java:215)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:533)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="SKIP" signature="verifyAddDestination()[pri:7, instance:com.Fullload_CDC.SqlToAdlsDM@193f604a]" name="verifyAddDestination" duration-ms="0" started-at="2020-04-14T12:02:19Z" depends-on-methods="com.Fullload_CDC.SqlToAdlsDM.verifySourceAdd" finished-at="2020-04-14T12:02:19Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SqlToAdlsDM.verifyAddDestination()[pri:7, instance:com.Fullload_CDC.SqlToAdlsDM@193f604a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SqlToAdlsDM.verifyAddDestination()[pri:7, instance:com.Fullload_CDC.SqlToAdlsDM@193f604a] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAddDestination -->
        <test-method status="SKIP" signature="verifyAddDataFlow()[pri:8, instance:com.Fullload_CDC.SqlToAdlsDM@193f604a]" name="verifyAddDataFlow" duration-ms="0" started-at="2020-04-14T12:02:19Z" depends-on-methods="com.Fullload_CDC.SqlToAdlsDM.verifyAddDestination" finished-at="2020-04-14T12:02:19Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SqlToAdlsDM.verifyAddDataFlow()[pri:8, instance:com.Fullload_CDC.SqlToAdlsDM@193f604a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SqlToAdlsDM.verifyAddDataFlow()[pri:8, instance:com.Fullload_CDC.SqlToAdlsDM@193f604a] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAddDataFlow -->
        <test-method status="SKIP" signature="verifyScheduledFlow()[pri:9, instance:com.Fullload_CDC.SqlToAdlsDM@193f604a]" name="verifyScheduledFlow" duration-ms="0" started-at="2020-04-14T12:02:19Z" depends-on-methods="com.Fullload_CDC.SqlToAdlsDM.verifyAddDataFlow" finished-at="2020-04-14T12:02:19Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SqlToAdlsDM.verifyScheduledFlow()[pri:9, instance:com.Fullload_CDC.SqlToAdlsDM@193f604a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SqlToAdlsDM.verifyScheduledFlow()[pri:9, instance:com.Fullload_CDC.SqlToAdlsDM@193f604a] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyScheduledFlow -->
        <test-method status="SKIP" signature="verifyFlowOnMontioringScreen()[pri:10, instance:com.Fullload_CDC.SqlToAdlsDM@193f604a]" name="verifyFlowOnMontioringScreen" duration-ms="0" started-at="2020-04-14T12:02:19Z" depends-on-methods="com.Fullload_CDC.SqlToAdlsDM.verifyScheduledFlow" finished-at="2020-04-14T12:02:19Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SqlToAdlsDM.verifyFlowOnMontioringScreen()[pri:10, instance:com.Fullload_CDC.SqlToAdlsDM@193f604a] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SqlToAdlsDM.verifyFlowOnMontioringScreen()[pri:10, instance:com.Fullload_CDC.SqlToAdlsDM@193f604a] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyFlowOnMontioringScreen -->
      </class> <!-- com.Fullload_CDC.SqlToAdlsDM -->
      <class name="com.Fullload_CDC.SqltoAzuresql">
        <test-method status="PASS" signature="Report(java.lang.String)[pri:0, instance:com.Fullload_CDC.SqltoAzuresql@550ee7e5]" name="Report" is-config="true" duration-ms="138" started-at="2020-04-14T12:02:03Z" finished-at="2020-04-14T12:02:03Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://cloudblaze-ui-react.azurewebsites.net/#]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Report -->
        <test-method status="FAIL" signature="init(java.lang.String)[pri:0, instance:com.Fullload_CDC.SqltoAzuresql@550ee7e5]" name="init" is-config="true" duration-ms="16304" started-at="2020-04-14T12:02:03Z" finished-at="2020-04-14T12:02:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[https://cloudblaze-ui-react.azurewebsites.net/#]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.SessionNotCreatedException">
            <message>
              <![CDATA[session not created
from chrome not reachable
  (Session info: chrome=80.0.3987.163)
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'LAPTOP-2G86F66K', ip: '192.168.29.96', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
Ordinal0 [0x00220AE3+1706723]
Ordinal0 [0x001868C1+1075393]
Ordinal0 [0x000FDE52+515666]
Ordinal0 [0x000F7C88+490632]
Ordinal0 [0x000F837B+492411]
Ordinal0 [0x000F92D5+496341]
Ordinal0 [0x000F4EE5+478949]
Ordinal0 [0x000FEC80+519296]
Ordinal0 [0x000ACA67+182887]
Ordinal0 [0x000ABDDD+179677]
Ordinal0 [0x000A9D4B+171339]
Ordinal0 [0x00091D4A+73034]
Ordinal0 [0x00092DC0+77248]
Ordinal0 [0x00092D59+77145]
Ordinal0 [0x0019BB37+1162039]
GetHandleVerifier [0x002BA7C6+508998]
GetHandleVerifier [0x002BA504+508292]
GetHandleVerifier [0x002CF617+594583]
GetHandleVerifier [0x002BB036+511158]
Ordinal0 [0x00193FFC+1130492]
Ordinal0 [0x0019D49B+1168539]
Ordinal0 [0x0019D603+1168899]
Ordinal0 [0x001B5B05+1268485]
BaseThreadInitThunk [0x770E6359+25]
RtlGetAppContainerNamedObjectPath [0x77697B74+228]
RtlGetAppContainerNamedObjectPath [0x77697B44+180]
(No symbol) [0x00000000]
]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.SessionNotCreatedException: session not created
from chrome not reachable
  (Session info: chrome=80.0.3987.163)
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'LAPTOP-2G86F66K', ip: '192.168.29.96', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
Ordinal0 [0x00220AE3+1706723]
Ordinal0 [0x001868C1+1075393]
Ordinal0 [0x000FDE52+515666]
Ordinal0 [0x000F7C88+490632]
Ordinal0 [0x000F837B+492411]
Ordinal0 [0x000F92D5+496341]
Ordinal0 [0x000F4EE5+478949]
Ordinal0 [0x000FEC80+519296]
Ordinal0 [0x000ACA67+182887]
Ordinal0 [0x000ABDDD+179677]
Ordinal0 [0x000A9D4B+171339]
Ordinal0 [0x00091D4A+73034]
Ordinal0 [0x00092DC0+77248]
Ordinal0 [0x00092D59+77145]
Ordinal0 [0x0019BB37+1162039]
GetHandleVerifier [0x002BA7C6+508998]
GetHandleVerifier [0x002BA504+508292]
GetHandleVerifier [0x002CF617+594583]
GetHandleVerifier [0x002BB036+511158]
Ordinal0 [0x00193FFC+1130492]
Ordinal0 [0x0019D49B+1168539]
Ordinal0 [0x0019D603+1168899]
Ordinal0 [0x001B5B05+1268485]
BaseThreadInitThunk [0x770E6359+25]
RtlGetAppContainerNamedObjectPath [0x77697B74+228]
RtlGetAppContainerNamedObjectPath [0x77697B44+180]
(No symbol) [0x00000000]

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:207)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
at com.CloudBlaze.Base.BaseClass.init(BaseClass.java:75)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.beforeRun(TestRunner.java:529)
at org.testng.TestRunner.run(TestRunner.java:497)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.SessionNotCreatedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="SKIP" signature="verifySourceAdd()[pri:1, instance:com.Fullload_CDC.SqltoAzuresql@550ee7e5]" name="verifySourceAdd" duration-ms="0" started-at="2020-04-14T12:02:19Z" finished-at="2020-04-14T12:02:19Z">
          <exception class="org.openqa.selenium.SessionNotCreatedException">
            <message>
              <![CDATA[session not created
from chrome not reachable
  (Session info: chrome=80.0.3987.163)
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'LAPTOP-2G86F66K', ip: '192.168.29.96', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
Ordinal0 [0x00220AE3+1706723]
Ordinal0 [0x001868C1+1075393]
Ordinal0 [0x000FDE52+515666]
Ordinal0 [0x000F7C88+490632]
Ordinal0 [0x000F837B+492411]
Ordinal0 [0x000F92D5+496341]
Ordinal0 [0x000F4EE5+478949]
Ordinal0 [0x000FEC80+519296]
Ordinal0 [0x000ACA67+182887]
Ordinal0 [0x000ABDDD+179677]
Ordinal0 [0x000A9D4B+171339]
Ordinal0 [0x00091D4A+73034]
Ordinal0 [0x00092DC0+77248]
Ordinal0 [0x00092D59+77145]
Ordinal0 [0x0019BB37+1162039]
GetHandleVerifier [0x002BA7C6+508998]
GetHandleVerifier [0x002BA504+508292]
GetHandleVerifier [0x002CF617+594583]
GetHandleVerifier [0x002BB036+511158]
Ordinal0 [0x00193FFC+1130492]
Ordinal0 [0x0019D49B+1168539]
Ordinal0 [0x0019D603+1168899]
Ordinal0 [0x001B5B05+1268485]
BaseThreadInitThunk [0x770E6359+25]
RtlGetAppContainerNamedObjectPath [0x77697B74+228]
RtlGetAppContainerNamedObjectPath [0x77697B44+180]
(No symbol) [0x00000000]
]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.SessionNotCreatedException: session not created
from chrome not reachable
  (Session info: chrome=80.0.3987.163)
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'LAPTOP-2G86F66K', ip: '192.168.29.96', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
Ordinal0 [0x00220AE3+1706723]
Ordinal0 [0x001868C1+1075393]
Ordinal0 [0x000FDE52+515666]
Ordinal0 [0x000F7C88+490632]
Ordinal0 [0x000F837B+492411]
Ordinal0 [0x000F92D5+496341]
Ordinal0 [0x000F4EE5+478949]
Ordinal0 [0x000FEC80+519296]
Ordinal0 [0x000ACA67+182887]
Ordinal0 [0x000ABDDD+179677]
Ordinal0 [0x000A9D4B+171339]
Ordinal0 [0x00091D4A+73034]
Ordinal0 [0x00092DC0+77248]
Ordinal0 [0x00092D59+77145]
Ordinal0 [0x0019BB37+1162039]
GetHandleVerifier [0x002BA7C6+508998]
GetHandleVerifier [0x002BA504+508292]
GetHandleVerifier [0x002CF617+594583]
GetHandleVerifier [0x002BB036+511158]
Ordinal0 [0x00193FFC+1130492]
Ordinal0 [0x0019D49B+1168539]
Ordinal0 [0x0019D603+1168899]
Ordinal0 [0x001B5B05+1268485]
BaseThreadInitThunk [0x770E6359+25]
RtlGetAppContainerNamedObjectPath [0x77697B74+228]
RtlGetAppContainerNamedObjectPath [0x77697B44+180]
(No symbol) [0x00000000]

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:207)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
at com.CloudBlaze.Base.BaseClass.init(BaseClass.java:75)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.beforeRun(TestRunner.java:529)
at org.testng.TestRunner.run(TestRunner.java:497)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.SessionNotCreatedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySourceAdd -->
        <test-method status="FAIL" signature="getResult(org.testng.ITestResult)[pri:0, instance:com.Fullload_CDC.SqltoAzuresql@550ee7e5]" name="getResult" is-config="true" duration-ms="2" started-at="2020-04-14T12:02:19Z" finished-at="2020-04-14T12:02:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name={null} status=CREATED method=SqltoAzuresql.verifySourceAdd()[pri:1, instance:com.Fullload_CDC.SqltoAzuresql@550ee7e5] output={null}]]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.CloudBlaze.Base.BaseClass.getResult(BaseClass.java:215)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:533)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="SKIP" signature="verifyAddDestination()[pri:2, instance:com.Fullload_CDC.SqltoAzuresql@550ee7e5]" name="verifyAddDestination" duration-ms="0" started-at="2020-04-14T12:02:19Z" depends-on-methods="com.Fullload_CDC.SqltoAzuresql.verifySourceAdd" finished-at="2020-04-14T12:02:19Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SqltoAzuresql.verifyAddDestination()[pri:2, instance:com.Fullload_CDC.SqltoAzuresql@550ee7e5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SqltoAzuresql.verifyAddDestination()[pri:2, instance:com.Fullload_CDC.SqltoAzuresql@550ee7e5] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAddDestination -->
        <test-method status="SKIP" signature="verifyAddDataFlow()[pri:3, instance:com.Fullload_CDC.SqltoAzuresql@550ee7e5]" name="verifyAddDataFlow" duration-ms="0" started-at="2020-04-14T12:02:19Z" depends-on-methods="com.Fullload_CDC.SqltoAzuresql.verifyAddDestination" finished-at="2020-04-14T12:02:19Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SqltoAzuresql.verifyAddDataFlow()[pri:3, instance:com.Fullload_CDC.SqltoAzuresql@550ee7e5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SqltoAzuresql.verifyAddDataFlow()[pri:3, instance:com.Fullload_CDC.SqltoAzuresql@550ee7e5] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAddDataFlow -->
        <test-method status="SKIP" signature="verifyScheduledFlow()[pri:4, instance:com.Fullload_CDC.SqltoAzuresql@550ee7e5]" name="verifyScheduledFlow" duration-ms="0" started-at="2020-04-14T12:02:19Z" depends-on-methods="com.Fullload_CDC.SqltoAzuresql.verifyAddDataFlow" finished-at="2020-04-14T12:02:19Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SqltoAzuresql.verifyScheduledFlow()[pri:4, instance:com.Fullload_CDC.SqltoAzuresql@550ee7e5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SqltoAzuresql.verifyScheduledFlow()[pri:4, instance:com.Fullload_CDC.SqltoAzuresql@550ee7e5] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyScheduledFlow -->
        <test-method status="SKIP" signature="verifyFlowOnMontioringScreen()[pri:5, instance:com.Fullload_CDC.SqltoAzuresql@550ee7e5]" name="verifyFlowOnMontioringScreen" duration-ms="0" started-at="2020-04-14T12:02:19Z" depends-on-methods="com.Fullload_CDC.SqltoAzuresql.verifyScheduledFlow" finished-at="2020-04-14T12:02:19Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SqltoAzuresql.verifyFlowOnMontioringScreen()[pri:5, instance:com.Fullload_CDC.SqltoAzuresql@550ee7e5] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SqltoAzuresql.verifyFlowOnMontioringScreen()[pri:5, instance:com.Fullload_CDC.SqltoAzuresql@550ee7e5] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:887)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyFlowOnMontioringScreen -->
        <test-method status="FAIL" signature="tearDown()[pri:0, instance:com.Fullload_CDC.SqltoAzuresql@550ee7e5]" name="tearDown" is-config="true" duration-ms="162" started-at="2020-04-14T12:02:19Z" finished-at="2020-04-14T12:02:19Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.CloudBlaze.Base.BaseClass.tearDown(BaseClass.java:235)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:425)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.Fullload_CDC.SqltoAzuresql -->
    </test> <!-- CloudBlaze Tests -->
  </suite> <!-- CloudBlaze Automation -->
</testng-results>
