<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="LAPTOP-2G86F66K" name="com.CloudBlaze.Onboarding.DataSources" tests="21" failures="0" timestamp="26 Feb 2020 11:13:41 GMT" time="245.383" errors="2">
  <testcase name="getResult" time="14.155" classname="com.CloudBlaze.Onboarding.DataSources">
    <error type="org.openqa.selenium.WebDriverException" message="chrome not reachable
  (Session info: chrome=80.0.3987.122)
Build info: version: &#039;3.12.0&#039;, revision: &#039;7c6e0b3&#039;, time: &#039;2018-05-08T14:04:26.12Z&#039;
System info: host: &#039;LAPTOP-2G86F66K&#039;, ip: &#039;192.168.0.15&#039;, os.name: &#039;Windows 10&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;1.8.0_181&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 80.0.3987.122, chrome: {chromedriverVersion: 80.0.3987.16 (320f6526c1632..., userDataDir: C:\Users\Lenovo\AppData\Loc...}, goog:chromeOptions: {debuggerAddress: localhost:53286}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 2a739492d48a3a5e765ee7f72bb94967">
      <![CDATA[org.openqa.selenium.WebDriverException: chrome not reachable
  (Session info: chrome=80.0.3987.122)
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'LAPTOP-2G86F66K', ip: '192.168.0.15', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 80.0.3987.122, chrome: {chromedriverVersion: 80.0.3987.16 (320f6526c1632..., userDataDir: C:\Users\Lenovo\AppData\Loc...}, goog:chromeOptions: {debuggerAddress: localhost:53286}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 2a739492d48a3a5e765ee7f72bb94967
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:289)
at com.CloudBlaze.Base.BaseClass.getScreenshot(BaseClass.java:213)
at com.CloudBlaze.Base.BaseClass.getResult(BaseClass.java:190)
at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- getResult -->
  <testcase name="verifyDataSourcesPageLink" time="4.564" classname="com.CloudBlaze.Onboarding.DataSources"/>
  <testcase name="verifyUrlOfDataSources" time="3.646" classname="com.CloudBlaze.Onboarding.DataSources"/>
  <testcase name="verifyComponentsOfStoragePage" time="3.626" classname="com.CloudBlaze.Onboarding.DataSources"/>
  <testcase name="verifyGridComponents" time="0.109" classname="com.CloudBlaze.Onboarding.DataSources"/>
  <testcase name="verifyColumnsOfGrid" time="0.235" classname="com.CloudBlaze.Onboarding.DataSources"/>
  <testcase name="verifyNumberOfRecords" time="0.016" classname="com.CloudBlaze.Onboarding.DataSources"/>
  <testcase name="verifyDataFactoryFields" time="0.031" classname="com.CloudBlaze.Onboarding.DataSources"/>
  <testcase name="sendGetConfigDataBricks" time="4.461" classname="com.CloudBlaze.Onboarding.DataSources"/>
  <testcase name="sendGetConfigSql" time="3.524" classname="com.CloudBlaze.Onboarding.DataSources"/>
  <testcase name="sendGetConfigBlob" time="3.496" classname="com.CloudBlaze.Onboarding.DataSources"/>
  <testcase name="sendGetBatch" time="3.519" classname="com.CloudBlaze.Onboarding.DataSources"/>
  <testcase name="verifyGridFields" time="0.032" classname="com.CloudBlaze.Onboarding.DataSources"/>
  <testcase name="verifyValidationsForSource" time="4.507" classname="com.CloudBlaze.Onboarding.DataSources"/>
  <testcase name="verifyValidationsForDestination" time="8.690" classname="com.CloudBlaze.Onboarding.DataSources"/>
  <testcase name="verifyAddDestination" time="18.417" classname="com.CloudBlaze.Onboarding.DataSources"/>
  <testcase name="verifySourceAdd" time="47.904" classname="com.CloudBlaze.Onboarding.DataSources"/>
  <testcase name="verifyReadBlob" time="122.776" classname="com.CloudBlaze.Onboarding.DataSources"/>
  <testcase name="sendGetrequest" time="1.675" classname="com.CloudBlaze.Onboarding.DataSources">
    <error type="java.io.FileNotFoundException" message="https://management.azure.com/subscriptions/07cb4a1a-1dae-487e-88ff-2d2bac272da3/resourceGroups/CB0Demo1/providers/Microsoft.DataFactory/factories/cb0oanfb2ihritaidemo1df/pipelines/Source_SQlADLS_Auto_metadataextractor?api-version=2018-06-01">
      <![CDATA[java.io.FileNotFoundException: https://management.azure.com/subscriptions/07cb4a1a-1dae-487e-88ff-2d2bac272da3/resourceGroups/CB0Demo1/providers/Microsoft.DataFactory/factories/cb0oanfb2ihritaidemo1df/pipelines/Source_SQlADLS_Auto_metadataextractor?api-version=2018-06-01
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
at sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
at com.CloudBlaze.Onboarding.DataSources.sendGetrequest(DataSources.java:865)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.io.FileNotFoundException: https://management.azure.com/subscriptions/07cb4a1a-1dae-487e-88ff-2d2bac272da3/resourceGroups/CB0Demo1/providers/Microsoft.DataFactory/factories/cb0oanfb2ihritaidemo1df/pipelines/Source_SQlADLS_Auto_metadataextractor?api-version=2018-06-01
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
at java.net.HttpURLConnection.getResponseCode(Unknown Source)
at java.net.HttpURLConnection.getResponseMessage(Unknown Source)
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseMessage(Unknown Source)
at com.CloudBlaze.Onboarding.DataSources.sendGetrequest(DataSources.java:855)
... 25 more
]]>
    </error>
  </testcase> <!-- sendGetrequest -->
  <testcase name="sendingPostRequest" time="0.000" classname="com.CloudBlaze.Onboarding.DataSources">
    <skipped/>
  </testcase> <!-- sendingPostRequest -->
  <testcase name="deleteSource" time="0.000" classname="com.CloudBlaze.Onboarding.DataSources">
    <skipped/>
  </testcase> <!-- deleteSource -->
</testsuite> <!-- com.CloudBlaze.Onboarding.DataSources -->
